on: push

name: Build and test

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Clippy
        run: cargo clippy --all-features -- -D warnings

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Format
        run: cargo fmt --all -- --check

  tailwind-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
      - name: Install Tailwind
        run: npm install -D tailwindcss @tailwindcss/cli
      - name: Install Dependencies
        run: npm install @tailwindcss/typography @tailwindcss/forms @tailwindcss/aspect-ratio
      - name: Build
        run: npx @tailwindcss/cli -o styles/main.css
      - name: Upload Style Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tailwind-style
          path: styles/main.css

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown
      - name: Install Trunk
        run: cargo install --locked trunk
      - name: Clean
        run: cargo clean
      - name: Download Style Artifact
        uses: actions/download-artifact@v5
        with:
          name: tailwind-style
          path: styles
      - name: Build
        run: trunk build --release --verbose