on: push

name: Build and test

on:
  workflow_run:
    workflows: ["Tailwind"]
    types:
      - completed

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown
      - name: Install Trunk
        run: cargo install --locked trunk
      - name: Clean
        run: cargo clean
      - name: Download CSS artifact
        uses: actions/download-artifact@v2
        with:
          name: tailwind-css
          path: style/
      - name: Build
        run: trunk build --release --verbose

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clippy
        run: cargo clippy --all-features -- -D warnings

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: cargo fmt --all -- --check